core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

from django.conf.urls.static import static
from django.views.generic import RedirectView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView
)
from account.token_views import customEmailTokenObtainView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('jobs/',include('jobs.urls')),
    path('',RedirectView.as_view(url='/account/login/',permanent=False)),
    path('api/',include('jobs.api_urls')),
    path('api/token/',customEmailTokenObtainView.as_view(),name='token_obtain_pair'),
    path('api/token/refresh',TokenRefreshView.as_view(),name='token_refresh'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/',views.job_create,name='job_create'),
    path('view_all_job/',views.view_All_Job,name='view_all_Job'),
    path('job/<int:id>/',views.job_detail,name='job_detail'),
    path('job_apply/<int:id>/',views.apply_job,name='apply_job'),
    path('recruiter/jobs',views.recruiter_job,name='recruiter_job'),
    path('edit/<int:job_id>/',views.edit_job,name='edit_job'),
    path('delete/<int:job_id>/',views.delete_job,name='delete_job'),
    path('applicats/<int:job_id>',views.view_applicants,name='view_applicants'),
    path('application/update/<int:application_id>/',views.update_application_status,name='update_application_status'),
]

jobs/models.py
from django.db import models
from django.conf import settings
# from .models import Job

# Create your models here.
JOB_TYPE_CHOICES = [
    ('Full Time','Full Time'),
    ('Part Time','Part Time'),
    ('Internship','Internship'),
    ('Contract','Contract')
]

class Job(models.Model):
    title = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    job_type = models.CharField(max_length=50,choices=JOB_TYPE_CHOICES)
    salary = models.CharField(max_length=100,blank=True)
    description = models.TextField()
    deadline =models.DateField()
    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.title} at {self.company}"


APPLICATION_STATUS_CHOICES = [
    ('applied','Applied'),
    ('shortlisted','Shortlisted'),
    ('interview','L1 Cleared'),
    ('interview_technical','Interview technical'),
    ('hr_cleared','HR Cleared'),
    ('rejected','Rejected'),
    ('offered','Offered'),
    ('on_hold','On Hold')
]

class JobApplication(models.Model):
    jobs = models.ForeignKey('Job',on_delete=models.CASCADE)
    student = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    applied_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20,choices=APPLICATION_STATUS_CHOICES,default='applied')
    status_notified = models.BooleanField(default=True)

    class Meta:
        unique_together = ('jobs','student')

    def __str__(self):
        return f"{self.student.email}+{self.jobs.title}"

jobs/forms.py
from django import forms
from .models import Job
import datetime
class JobPostForm(forms.ModelForm):
    class Meta:
        model =Job
        fields = ['title','description','company','location','job_type','deadline','salary']
        widgets ={
            'description':forms.Textarea(attrs={'rows':4}),
            'deadline': forms.DateInput(attrs={'class': 'form-control', 'type':'date', 'min': datetime.date.today().strftime('%Y-%m-%d')}),
        }

        def __init__(self,*args,**kwargs):
            super(JobPostForm,self).__init__(*args,**kwargs)
            for field in self.fields.values():
                field.wedget.attrs.update({'class':'form-control'})
            

jobs/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import JobPostForm
from .models import Job,JobApplication ,APPLICATION_STATUS_CHOICES
from django.contrib import messages


# Create your views here.

@login_required
def job_create(request):
    if not request.user.role == 'recruiter':
        return redirect('student_dashboard')
    
    if request.method == 'POST':
        form = JobPostForm(request.POST)
        if form.is_valid():
            job = form.save(commit=False)
            job.posted_by = request.user
            job.save()
            messages.success(request,'Job Posted SuccessFully')
            return redirect('recruiter_dashboard')
    else:
        form = JobPostForm()
    return render(request,'jobs/jobs_create.html',{'form_data':form})


@login_required
def recruiter_job(request):
    if not request.user.role == 'recruiter':
        return redirect('student_dashboard')
    
    jobs = Job.objects.filter(posted_by=request.user).order_by('-created_at')
    return render(request,'jobs/recruiter_jobs.html',{'jobs':jobs})




def view_All_Job(request):
    if not request.user.role == 'student':
        return redirect('recruiter_dashboard')
    job_data = Job.objects.all()
    return render(request,'account/view_all_jobs.html',{'job_key': job_data})
        

def job_detail(request,id):
    job = get_object_or_404(Job,id=id)
    return render(request,'jobs/job_detail.html',{'job_demo':job})

def apply_job(request,id):
    if not request.user.is_authenticated or not request. user.role == 'student':
        messages.error(request,"Only student can apply")
        return redirect('login')
    job = get_object_or_404(Job,id=id)
    already_applied = JobApplication.objects.filter(jobs=job,student=request.user).exists()
    if already_applied:
        messages.warning(request,"you have already applied for this Job")
    else:
        JobApplication.objects.create(jobs=job,student=request.user)
        messages.success(request,"Successfully applied to the job")

    return redirect('job_detail',id=id)

@login_required
def edit_job(request,job_id):
    job = get_object_or_404(Job,id=job_id,posted_by=request.user)
    if request.method =='POST':
        form =JobPostForm(request.POST,instance=job)
        if form.is_valid():
            form.save()
            messages.success(request,"Job Updated Successfully")
            return redirect('recruiter_dashboard')
    else:
        form = JobPostForm(instance=job)
    return render(request,'jobs/edit_job.html',{'form_data':form})

@login_required
def delete_job(request,job_id):
    job = get_object_or_404(Job,id=job_id,posted_by=request.user)

    if request.method == 'POST':
        job.delete()
        messages.info(request,"Job Deleted Successfully")
        return redirect('recruiter_dashboard')
    return render(request,'jobs/recruiter_jobs.html',{'job_key': job})


@login_required
def view_applicants(request,job_id):
        job = get_object_or_404(Job,id=job_id,posted_by=request.user)
        application = JobApplication.objects.filter(jobs=job).select_related('student')
        return render(request,'jobs/view_applicants.html',{'job':job,'applications':application ,'status_choices':APPLICATION_STATUS_CHOICES })

@login_required
def update_application_status(request,application_id):
    if request.method == 'POST':
        application = get_object_or_404(JobApplication,id=application_id)
        new_status = request.POST.get('status')
        if new_status in dict(APPLICATION_STATUS_CHOICES):
            application.status = new_status
            application.status_notified = False
            application.save()
            messages.success(request,f"Application Status updated to {new_status.title()} Successfully")
        else:
            messages.error(request,'Invalid Status Provided')
    return redirect('view_applicants',job_id=application.jobs.id)

jobs/templates/jobs/edit_job.html
{% extends 'account/base.html' %}

{% block title %}Edit Job{% endblock %}

{% block content %}
<div class="container mt-5 col-md-6">
    <h2 class="mb-4 text-primary">Edit Job</h2>
    <form method="POST">
        {% csrf_token %}
        {% for field in form_data %}
            <div class="mb-3">
                <label class="text-danger">{{ field.label }}</label>
            {{ field }}
            {% if field.errors %}
                <div class="text-danger small">
                    {% for error in field.errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-danger w-100">Update Job</button>
    </form>
</div>
{% endblock %}

jobs/templates/jobs/job_detail.html
{% extends 'account/base.html' %}
{% block title %}Post a Job {% endblock %}

{% block content %}
<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-lg-8">

      <div class="card shadow-lg border-0">
        <div class="card-body">
          
          
          <h2 class="card-title text-dark mb-2">
            {{ job_demo.title }}
            <span class="badge bg-info text-dark ms-2">{{ job_demo.job_type|title }}</span>
          </h2>

          
          <h5 class="text-muted mb-4">
            <i class="bi bi-building"></i> {{ job_demo.company_name }} &nbsp;|&nbsp; 
            <i class="bi bi-currency-rupee"></i> {{ job_demo.salary }}
          </h5>

          
          <p class="mb-3">
            <i class="bi bi-geo-alt-fill text-danger"></i> <strong>Location:</strong> {{ job_demo.location }}
          </p>

          
          <div class="mb-4">
            <h6><i class="bi bi-file-earmark-text-fill"></i> Job Description:</h6>
            <p class="text-justify">{{ job_demo.description }}</p>
          </div>

          
          <div class="d-flex justify-content-between align-items-center">
            <a href="{% url 'view_all_Job' %}" class="btn btn-secondary">
              ← Back to All Jobs
            </a>
          {% if user.is_authenticated and user.role == 'student' %}
            <form method="POST" action="{% url 'apply_job' job_demo.id  %}">
              {%  csrf_token %} 
               <button class="text-success mt-3">Apply Now</button>
            </form>

          {% else %}
            <p class="text-danger mt-3">Login as student to apply</p>
          {% endif %}
          </div>

        </div>
      </div>

    </div>
  </div>
</div>
{% endblock %}

jobs/templates/jobs/jobs_create.html
{% extends 'account/base.html' %}
{% load widget_tweaks %}
{% block title %}Post a New Job{% endblock %}

{% block content %}
    <div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card shadow-lg border-0">
        <div class="card-header bg-dark text-white text-center py-3">
          <h3 class="mb-0">Post a New Job</h3>
        </div>
        <div class="card-body p-4">
          <form method="POST" novalidate>
            {% csrf_token %}

            <div class="form-floating mb-3">
              {{ form_data.title|add_class:"form-control" }}
              <label for="{{ form_data.title.id_for_label }}">Job Title</label>
            </div>

            <div class="form-floating mb-3">
              {{ form_data.description|add_class:"form-control" }}
              <label for="{{ form_data.description.id_for_label }}">Description</label>
            </div>

            <div class="form-floating mb-3">
              {{ form_data.company|add_class:"form-control" }}
              <label for="{{ form_data.company.id_for_label }}">Company</label>
            </div>

            <div class="form-floating mb-3">
              {{ form_data.location|add_class:"form-control" }}
              <label for="{{ form_data.location.id_for_label }}">Location</label>
            </div>

            <div class="form-floating mb-3">
              {{ form_data.job_type|add_class:"form-select" }}
              <label for="{{ form_data.job_type.id_for_label }}">Job Type</label>
            </div>

            <div class="form-floating mb-3">
              {{ form_data.deadline|add_class:"form-control" }}
              <label for="{{ form_data.deadline.id_for_label }}">Deadline</label>
            </div>

            <div class="form-floating mb-4">
              {{ form_data.salary|add_class:"form-control" }}
              <label for="{{ form_data.salary.id_for_label }}">Salary (₹)</label>
            </div>

            <button type="submit" class="btn btn-success w-100 py-2 fw-bold">
              Post Job
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
  document.addEventListener('DOMContentLoaded',function(){
    const deadlineInput = document.querySelector('input[name="deadline"]');
    const form = document.querySelector('form');

    if(deadlineInput){
      const today = new Date().toISOString().split('T')[0];
      deadlineInput.setAttribute('min',today);
    }

    if(form && deadlineInput){
      form.addEventListener('submit',function(e){
        const selectedDate = new Date(deadlineInput.value);
        const today = new Date();
        today.setHours(0,0,0,0);

        if(selectedDate < today){
          e.preventDefault();
          Swal.fire({
            icon:'error',
            title:'Invalid Deadline',
            text:'Deadline Cannot be in the Past!'
          });
        }

      });
    }
  });
</script>
{% endblock %}

jobs/templates/jobs/recruiter_jobs.html
{% extends 'account/base.html' %}
{% block title %}  {{ user_type }}  SignUp.  {% endblock %}

{% block content %}

    <div class="container mt-5">
        
        
    <br>
    <table id="jobsTable" class="table table-bordered table-striped text-center">
        <thead class="table-dark">
            <tr>
                <th>title</th>
                <th>company</th>
                <th>location</th>
                <th>job Type</th>
                <th>posted by</th>
                <th>Application</th>
                <th>Action</th>
            </tr>
        </thead>
    <tbody>
        {% for item in jobs %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.company }}</td>
            <td>{{ item.location}}</td>
            <td>{{ item.job_type}}</td>
            <td>{{ item.posted_by}}</td>
            <td>
                <a href="{% url 'view_applicants' item.id%}">{{ item.jobapplication_set.count }}</a>
            <td>
                <a href="{% url 'edit_job' item.id %}" class="btn btn-sm btn-warning">Edit</a>

                <form action="{% url 'delete_job' item.id %}" method="POST" style="display:  inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure You Want to delete')">Delete</button>
                </form>
            </td>
        </tr>


    {% endfor %}
    </tbody>
    </table>
    </div>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
<script src="https://code.jquery.com/jquery-3.7.0.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
<script>
        $(document).ready(function () {
        $('#jobsTable').DataTable();
    });

</script>
{% endblock %}

jobs/templates/jobs/view_applicants.html
{% extends 'account/base.html' %}
{% block title %}  {{ user_type }}  SignUp.  {% endblock %}

{% block content %}

<div class="container mt-4">
    <h3 class="mb-4"> Applicants for <strong>{{ job.tittle}}</strong></h3>

    {% if applications %}
    <table class="table table-bordered table-hover">
        <thead class="table-dark">
            <tr>
                <th>Full Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Resume</th>
                <th>Applide On</th>
                <th>Status</th>
            </tr>
        </thead>

        <tbody>
            {% for app in applications %}
            <tr>
                <td>{{ app.student.full_name}}</td>
                <td>{{ app.student.email}}</td>
                <td>{{ app.student.phone}}</td>
                <td>
                    {% if app.student.resume %}
                        <a href="{{  app.student.resume.url }}" target="_blank">Download</a>
                        {% else %}
                            not Upload
                        {% endif %}
                </td>
                <td>{{ app.applied_at|date:"d M Y, H:i"}}</td>
            

            <td>
                <form method="POST" action="{% url 'update_application_status' app.id%}">
                    {% csrf_token %}
                    <select name="status" class="form-select form-select-sm">
                        {% for value,label in status_choices %}
                        <option value="{{ value }}" {% if value == app.status %}selected{% endif %}>{{ label }}</option>
                        {% endfor %}
                    </select>
                    <button type="submit" class="btn btn-sm btn-outline-primary mt-1">Update</button>
                </form>
            </td>
        </tr>
     {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>No Application</p>
    {% endif %}
</div>
{% endblock %}